def multisearch(regexes: str):
    ...
    
def search(regex: str):
    ...
    
def list_folder(folder_path: str):
    ...

def search_folders_multi(regexes: str):
    ...

def search_folders(regex: str):
    ...